setup:
  blend_path: "../renderTest/susans.blend" 
  render_output_dir: "/path/to/output" # not yet implemented
  #blender_exe_path: "C:/Program Files/Blender Foundation/Blender 4.0/blender.exe"
  blender_exe_path: "C:/Program Files/Blender Foundation/Blender 3.6/blender.exe"