setup:
  blend_path: "/path/to/project.blend" # not yet implemented
  render_output_dir: "/path/to/output" # not yet implemented
  blender_exe_path: "C:/Program Files/Blender Foundation/Blender 4.0/blender.exe"

logging:
  level: "INFO"  # Options: INFO, ERROR
  log_file: "/path/to/render_manager.log" # not yet implemented
