setup:
  blend_download_path: "/blend/blend.blend" 
  render_output_dir: "/render"
  blender_exe_path: "C:/Program Files/Blender Foundation/Blender 4.0/blender.exe" 

logging:
  level: "INFO"  # Options: INFO, ERROR
  log_file: "/path/to/render_manager.log" # not yet implemented
